### ISSUE TITLE
Issue installing citation.vim on Mac OS X 10.11.4, Vim 7.4.1129

### ISSUE THREAD

**Issue by mhoffman** [rafaqz/citation.vim#1]
Hi

thanks for this awesome looking plugin. I followed the installation [instructions](https://github.com/rafaqz/citation.vim#usage) on Mac OS X 10.11.4, Vim 7.4.1129, and Vundle 0.10.2. When I try the keyboard shortcut or command for citation insertion

     :<C-u>Unite -buffer-name=citation   -start-insert -default-action=append      bibtex

I only the see message 

```
[unite.vim] Invalid source name "bibtex" is detected.                                                                                                              
[unite.vim] unite.vim: Invalid source
Press ENTER or type command to continue
```

Any pointers at how I could resolve this? Is there a good way to debug this and interact more directly w/ the plugin?

Best.

P.S.: I use the zotero standalone installation and set 

    let g:citation_vim_zotero_folder=["~/Library/Application Support/Zotero/Profiles/<random>.default/zotero"]

but I also tried a valid `*.bib` file with 

    let g:citation_vim_mode="bibtex"

**Comment by rafaqz** [comment]
Hey sorry I accidentally left that line in the readme  from before zotero was included... Fixed now!
Use citation/key or citation/key_inner to cite inline without the brackets.

Entering :Unite citation will give you a list of possible sources.

**Comment by rafaqz** [comment]
If you have any more issues paste your config here and some system details, I'm not sure how much this plugin has been used outside of my setup and zotero and better_bibtex have a habit of changing things in random ways between versions.

**Comment by mhoffman** [comment]
Thx, for the heads up!

My [vimrc](https://gist.github.com/8720010b3826af951b2dfdfb892a441c ) is long and messy :-) and [this is the output](https://gist.github.com/a1a101f871d9f81d2e945c2e061bec0c) of `vim --version`.

When I now run one of the citation/key command

    :<C-u>Unite -buffer-name=citation   -start-insert -default-action=append      citation/key<cr>)

I get
```
[unite.vim] function <SNR>110_call_unite[33]..unite#start[1]..unite#start#standard[50]..unite#candidates#_recache[74]..<SNR>159_recache_candidates_loop[42]..<SNR>159_get_source_cand
idates[40]..501[3]..<SNR>156_get_source, line 11
[unite.vim] Vim(let):Traceback (most recent call last):
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is citation/key
```
If I interpret this correctly this points [here](https://github.com/rafaqz/citation.vim/blob/master/autoload/unite/sources/citation.vim#L118), unfortunately it's beyond my vimL capabilities so far to get a better backtrace from there.

**Comment by rafaqz** [comment]
Have you set your cache path? would be good if I gave that a clearer warning...

```
  let g:citation_vim_cache_path='~/.vim/your_cache_path'
```
If yes are you using the latest zotero and better_bibtex plugins?

**Comment by rafaqz** [comment]
I see you have... make sure it exists at least!

Probably remove the collection variable too you don't need it (see recent readme changes). But that wouldn't cause an error... this might be due to zotero/better_bibtex plugin. Try just using bibtex for the mode and see if that at least works with just your bibtex file, then we can look into zotero.

**Comment by rafaqz** [comment]
Ok after looking at your vimrc and the readme one problem is the brackets around the filename. that is also outdated. Remove those and see how it goes. Thanks for weeding out all these errors in the readme!

**Comment by rafaqz** [comment]
Also you currently need to set both zotero and bibtex file paths. Thats a bug.

**Comment by rafaqz** [comment]
The filename bug is fixed in master see how that goes.

**Comment by mhoffman** [comment]
Thanks, I installed the latest version from github. Here are my current citation specific settings in my `~/.vimrc`:
```
" Zotero plugin settings
nmap <space> [unite]
nnoremap [unite] <nop>
let g:citation_vim_zotero_folder="/Users/maxjh/Library/Application Support/Zotero/Profiles/y9hwubw4.default"
let g:citation_vim_bibtex_file="/Users/maxjh/stanford/My Library.bib"
let g:citation_vim_mode="bibtex"
let g:citation_vim_cache_path="/Users/maxjh/.vim/cache_path"
let g:citation_vim_collection="My Library"

let g:citation_vim_outer_prefix="["
let g:citation_vim_inner_prefix="@"
let g:citation_vim_suffix="]"
nnoremap <silent><leader>zk       :<C-u>Unite -buffer-name=citation   -start-insert -default-action=append      citation/key<cr>
nnoremap <silent><leader>za       :<C-u>Unite -buffer-name=citation   -start-insert -default-action=append      citation/author<cr>
```
All defined directories and files exists and the *.bib file has well-formed  content.

When I try `... citation_vim_mode="zotero"` I still receive
```
[unite.vim] function <SNR>110_call_unite[33]..unite#start[1]..unite#start#standard[50]..unite#candidates#_recache[74]..<SNR>159_recache_candidates_loop[42]..<SNR>159_get_source_cand
idates[40]..501[3]..<SNR>156_get_source, line 11
[unite.vim] Vim(let):Traceback (most recent call last):
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is citation/key
```
and then a horizontal empty split buffer appears in insert mode. The cache directory exists but in `zotero` mode it seems to remain empty. 

In `bibtex` mode first nothing seems to happen for a few seconds, no error message appear, then again an empty horizontal split appears in insert mode. This steps seems to fill my cache directory w/ a text file named `citation_vim_cache`.  It has a size of almost 4M and looks like some serialized python objects.  I have also seen an zotero.sqlite during testing but I am not sure what steps it takes to reproduce this.

I also ran the `test.py` script that I gleaned from #2. It dumps a summary of my zotero database to stdout. It also prints an error like
```
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    print(desc)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2236' in position 7: ordinal not in range(128)
``` 
to STDERR. I found that set `export PYTHONIOENCODING=utf-8` as recommended [in this Stackoverflow Thread](http://stackoverflow.com/questions/3224268/python-unicode-encode-error) this error message dissappears. However when I try the actual plugin from the same shell using vim everything remains as broken as before. I am not sure however whether this environment variable is picked up from inside the vim plugin.  However maybe some encoding issues could explain some of our trouble. I would guess that a lot of zotero collection typically contain one or more different encodings because they a screenscraped from various source in different countries. Maybe some encoding `.encode('utf-8', 'ignore')` in some right place could serve as a stop gap measure. Shall I send you my zotero bibtex export private for debugging?
Please let me know if I can be of any help gathering more info.

**Comment by rafaqz** [comment]
Great! getting somewhere at least. You should remove this line:

```
let g:citation_vim_collection="My Library"
```
As the base library is not actually a collection (set collection with :Unite citation_collection if you need to or use one from that list)

Hopefully that gets bibtex working. I'll look into utf8 for getting zotero working.

**Comment by rafaqz** [comment]
Looks like the unicode error is just with your python settings printing the test output to the command line.

Does the zotero test with `export PYTHONIOENCODING=utf-8` set actually print out all your citations?

**Comment by rafaqz** [comment]
Try the latest version, might fix your issues as well.
https://github.com/rafaqz/citation.vim/issues/2#issuecomment-243946600

Otherwise send my your zotero.sqlite and bettet-bibtex folder and I'll get it working.

**Comment by sappo** [comment]
@mhoffman change `g:citation_vim_zotero_folder` to `g:citation_vim_zotero_path`. I fixed the reference in the README in #3
